apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  template:
    spec:
      containers:
        - name: cert-manager-controller
          volumeMounts:
            - name: cacerts
              mountPath: /etc/ssl/certs/house_ca_root.pem
              subPath: house_ca_root.pem
      volumes:
        - name: cacerts
          configMap:
            name: house-ca-cert
